import { useState, useEffect, useMemo } from 'react';
import { useTaskContext } from '../context/TaskContext';
import { generateMilestones, createMilestone } from '../utils/milestone';
import './MilestoneBoard.css';

export default function MilestoneBoard({ onEditTask }) {
  const { allTasks, milestones, setMilestones, updateTask, deleteTask } = useTaskContext();
  const [editingId, setEditingId] = useState(null);
  const [editForm, setEditForm] = useState({});
  const [showAddForm, setShowAddForm] = useState(false);
  const [newMilestone, setNewMilestone] = useState({ title: '', deadline: '' });
  const [autoMilestones, setAutoMilestones] = useState([]);

  // Generate auto milestones when tasks change
  useEffect(() => {
    let mounted = true;
    generateMilestones(allTasks).then(generated => {
      if (mounted) {
        setAutoMilestones(generated);
      }
    });
    return () => { mounted = false; };
  }, [allTasks]);
  
  // Merge auto milestones with manual ones
  const mergedMilestones = useMemo(() => {
    const manualOnes = milestones.filter(m => !m.isAutoGenerated);
    // Combine: manual + regenerated auto milestones
    return [...manualOnes, ...autoMilestones];
  }, [milestones, autoMilestones]);

  const handleEdit = (milestone) => {
    setEditingId(milestone.id);
    setEditForm({ ...milestone });
  };

  const handleSaveEdit = () => {
    if (!editForm.title.trim()) return;
    
    setMilestones(prev => prev.map(m => 
      m.id === editingId 
        ? { ...m, ...editForm, isAutoGenerated: false }
        : m
    ));
    setEditingId(null);
    setEditForm({});
  };

  const handleCancelEdit = () => {
    setEditingId(null);
    setEditForm({});
  };

  const handleDelete = (id) => {
    if (window.confirm('删除此里程碑？')) {
      setMilestones(prev => prev.filter(m => m.id !== id));
    }
  };

  const handleAddMilestone = () => {
    if (!newMilestone.title.trim() || !newMilestone.deadline) return;
    
    const milestone = createMilestone(
      newMilestone.title,
      newMilestone.deadline
    );
    setMilestones(prev => [...prev, milestone]);
    setNewMilestone({ title: '', deadline: '' });
    setShowAddForm(false);
  };

  const handleTaskClick = (taskId) => {
    const task = allTasks.find(t => t.id === taskId);
    if (task) onEditTask(task);
  };

  const toggleTaskInMilestone = (milestoneId, taskId) => {
    setMilestones(prev => prev.map(m => {
      if (m.id !== milestoneId) return m;
      const hasTask = m.taskIds.includes(taskId);
      return {
        ...m,
        taskIds: hasTask 
          ? m.taskIds.filter(id => id !== taskId)
          : [...m.taskIds, taskId]
      };
    }));
  };

  return (
    <div className="milestone-board">
      <div className="milestone-header">
        <h2>🎯 里程碑</h2>
        <button 
          className="btn-add-milestone"
          onClick={() => setShowAddForm(true)}
        >
          ➕ 新建里程碑
        </button>
      </div>

      {showAddForm && (
        <div className="milestone-add-form">
          <input
            type="text"
            placeholder="里程碑标题"
            value={newMilestone.title}
            onChange={e => setNewMilestone(prev => ({ ...prev, title: e.target.value }))}
            autoFocus
          />
          <input
            type="date"
            value={newMilestone.deadline}
            onChange={e => setNewMilestone(prev => ({ ...prev, deadline: e.target.value }))}
          />
          <button onClick={handleAddMilestone}>添加</button>
          <button onClick={() => setShowAddForm(false)}>取消</button>
        </div>
      )}

      <div className="milestone-list">
        {mergedMilestones.length === 0 ? (
          <div className="milestone-empty">
            <p>暂无里程碑</p>
            <small>创建带有截止日期的任务后，系统会自动生成里程碑</small>
          </div>
        ) : (
          mergedMilestones.map(milestone => {
            const isEditing = editingId === milestone.id;
            const milestoneTasks = milestone.taskIds
              .map(id => allTasks.find(t => t.id === id))
              .filter(Boolean);

            return (
              <div 
                key={milestone.id} 
                className="milestone-card"
                style={{ borderLeftColor: milestone.color }}
              >
                {isEditing ? (
                  <div className="milestone-edit-form">
                    <input
                      type="text"
                      value={editForm.title}
                      onChange={e => setEditForm(prev => ({ ...prev, title: e.target.value }))}
                      placeholder="标题"
                    />
                    <input
                      type="date"
                      value={editForm.deadline}
                      onChange={e => setEditForm(prev => ({ ...prev, deadline: e.target.value }))}
                    />
                    <div className="milestone-edit-actions">
                      <button onClick={handleSaveEdit}>保存</button>
                      <button onClick={handleCancelEdit}>取消</button>
                    </div>
                  </div>
                ) : (
                  <>
                    <div className="milestone-card-header">
                      <h3>{milestone.title}</h3>
                      <div className="milestone-card-actions">
                        <button 
                          className="btn-icon"
                          onClick={() => handleEdit(milestone)}
                          title="编辑"
                        >
                          ✏️
                        </button>
                        <button 
                          className="btn-icon"
                          onClick={() => handleDelete(milestone.id)}
                          title="删除"
                        >
                          🗑️
                        </button>
                      </div>
                    </div>
                    <div className="milestone-date">
                      📅 {milestone.deadline}
                    </div>
                    <div className="milestone-tasks">
                      {milestoneTasks.length > 0 ? (
                        milestoneTasks.map(task => (
                          <div 
                            key={task.id} 
                            className="milestone-task-item"
                            onClick={() => handleTaskClick(task.id)}
                          >
                            <span className={`status-dot ${task.status}`}></span>
                            <span className="task-title">{task.title}</span>
                            <button 
                              className="btn-remove-task"
                              onClick={(e) => {
                                e.stopPropagation();
                                toggleTaskInMilestone(milestone.id, task.id);
                              }}
                            >
                              ×
                            </button>
                          </div>
                        ))
                      ) : (
                        <div className="milestone-empty-tasks">
                          暂无关联任务
                        </div>
                      )}
                    </div>
                    {milestone.isAutoGenerated && (
                      <div className="milestone-auto-badge">自动生成</div>
                    )}
                  </>
                )}
              </div>
            );
          })
        )}
      </div>
    </div>
  );
}
