/**
 * Milestone Generation Logic
 * Automatically identifies deadline clusters as milestones
 */

import { v4 as uuidv4 } from 'uuid';

const MILESTONE_COLORS = [
  '#3b82f6', // blue
  '#8b5cf6', // purple
  '#ec4899', // pink
  '#f97316', // orange
  '#14b8a6', // teal
  '#eab308', // yellow
  '#6366f1', // indigo
  '#22c55e', // green
];

/**
 * Generate milestones from tasks with deadlines
 * Groups tasks with deadlines within 3 days of each other
 * @param {Array} tasks - All tasks
 * @returns {Array} Array of milestone objects
 */
export function generateMilestones(tasks) {
  // Filter tasks with deadlines that are not done
  const tasksWithDeadlines = tasks
    .filter(t => t.dueDate && t.status !== 'done')
    .sort((a, b) => new Date(a.dueDate) - new Date(b.dueDate));

  if (tasksWithDeadlines.length === 0) return [];

  const milestones = [];
  let currentCluster = [];
  let clusterStartDate = null;

  const addCluster = (cluster) => {
    if (cluster.length === 0) return;
    
    const dates = cluster.map(t => new Date(t.dueDate));
    const minDate = new Date(Math.min(...dates));
    const maxDate = new Date(Math.max(...dates));
    
    // Generate milestone title based on date range
    const startStr = minDate.toLocaleDateString('zh-CN', { month: 'short', day: 'numeric' });
    const endStr = minDate.toDateString() === maxDate.toDateString() 
      ? '' 
      : '-' + maxDate.toLocaleDateString('zh-CN', { month: 'short', day: 'numeric' });
    
    const milestone = {
      id: uuidv4(),
      title: `📍 ${startStr}${endStr} 里程碑`,
      deadline: minDate.toISOString().split('T')[0],
      taskIds: cluster.map(t => t.id),
      color: MILESTONE_COLORS[milestones.length % MILESTONE_COLORS.length],
      isAutoGenerated: true
    };

    // If single task, use task title
    if (cluster.length === 1) {
      milestone.title = `📍 ${cluster[0].title}`;
      milestone.deadline = cluster[0].dueDate;
    }

    milestones.push(milestone);
  };

  for (const task of tasksWithDeadlines) {
    const taskDate = new Date(task.dueDate);
    taskDate.setHours(0, 0, 0, 0);

    if (currentCluster.length === 0) {
      currentCluster = [task];
      clusterStartDate = taskDate;
    } else {
      // Check if within 3 days of cluster start
      const daysDiff = Math.ceil((taskDate - clusterStartDate) / (1000 * 60 * 60 * 24));
      
      if (daysDiff <= 3) {
        currentCluster.push(task);
      } else {
        // Save current cluster and start new one
        addCluster(currentCluster);
        currentCluster = [task];
        clusterStartDate = taskDate;
      }
    }
  }

  // Don't forget the last cluster
  addCluster(currentCluster);

  return milestones;
}

/**
 * Create a manual milestone
 */
export function createMilestone(title, deadline, taskIds = [], color = null) {
  return {
    id: uuidv4(),
    title,
    deadline,
    taskIds,
    color: color || MILESTONE_COLORS[Math.floor(Math.random() * MILESTONE_COLORS.length)],
    isAutoGenerated: false
  };
}
