/**
 * Milestone Tests - CommonJS module test
 * Tests for generateMilestones, createMilestone, MILESTONE_COLORS
 */

const { describe, it, beforeEach } = require('node:test');
const assert = require('node:assert');

// Mock localStorage
const localStorageMock = {
  store: {},
  getItem(key) {
    return this.store[key] || null;
  },
  setItem(key, value) {
    this.store[key] = value;
  },
  removeItem(key) {
    delete this.store[key];
  },
  clear() {
    this.store = {};
  }
};

global.localStorage = localStorageMock;

const { generateMilestones, createMilestone, MILESTONE_COLORS } = require('../src/utils/milestone.js');

describe('Milestone Module', () => {
  describe('MILESTONE_COLORS', () => {
    it('should have 8 colors defined', () => {
      assert.strictEqual(MILESTONE_COLORS.length, 8);
    });

    it('should contain valid hex colors', () => {
      for (const color of MILESTONE_COLORS) {
        assert.ok(color.startsWith('#'));
        assert.strictEqual(color.length, 7);
      }
    });
  });

  describe('createMilestone', () => {
    it('should create a milestone with all fields', () => {
      const milestone = createMilestone('Test Milestone', '2024-12-31', ['task-1', 'task-2']);
      
      assert.ok(milestone.id);
      assert.strictEqual(milestone.title, 'Test Milestone');
      assert.strictEqual(milestone.deadline, '2024-12-31');
      assert.deepStrictEqual(milestone.taskIds, ['task-1', 'task-2']);
      assert.strictEqual(milestone.isAutoGenerated, false);
    });

    it('should generate unique IDs', () => {
      const m1 = createMilestone('Milestone 1', '2024-12-31');
      const m2 = createMilestone('Milestone 2', '2024-12-31');
      
      assert.notStrictEqual(m1.id, m2.id);
    });

    it('should use provided color if given', () => {
      const milestone = createMilestone('Test', '2024-12-31', [], '#FF0000');
      assert.strictEqual(milestone.color, '#FF0000');
    });

    it('should assign random color from palette if not provided', () => {
      const milestone = createMilestone('Test', '2024-12-31');
      assert.ok(MILESTONE_COLORS.includes(milestone.color));
    });
  });

  describe('generateMilestones', () => {
    it('should return empty array when no tasks with deadlines', async () => {
      const tasks = [
        { id: 'task-1', title: 'Task without deadline', status: 'todo' }
      ];
      
      const result = await generateMilestones(tasks);
      assert.deepStrictEqual(result, []);
    });

    it('should return empty array when all tasks are done', async () => {
      const tasks = [
        { id: 'task-1', title: 'Done task', status: 'done', dueDate: '2024-12-31' }
      ];
      
      const result = await generateMilestones(tasks);
      assert.deepStrictEqual(result, []);
    });

    it('should create one milestone for single task', async () => {
      const tasks = [
        { id: 'task-1', title: 'Task 1', status: 'todo', dueDate: '2024-12-31' }
      ];
      
      const result = await generateMilestones(tasks);
      
      assert.strictEqual(result.length, 1);
      assert.strictEqual(result[0].taskIds.length, 1);
      assert.strictEqual(result[0].taskIds[0], 'task-1');
    });

    it('should group tasks within 3 days into one milestone', async () => {
      const tasks = [
        { id: 'task-1', title: 'Task 1', status: 'todo', dueDate: '2024-12-01' },
        { id: 'task-2', title: 'Task 2', status: 'todo', dueDate: '2024-12-02' },
        { id: 'task-3', title: 'Task 3', status: 'todo', dueDate: '2024-12-03' }
      ];
      
      const result = await generateMilestones(tasks);
      
      assert.strictEqual(result.length, 1);
      assert.strictEqual(result[0].taskIds.length, 3);
    });

    it('should create separate milestones for tasks more than 3 days apart', async () => {
      const tasks = [
        { id: 'task-1', title: 'Task 1', status: 'todo', dueDate: '2024-12-01' },
        { id: 'task-2', title: 'Task 2', status: 'todo', dueDate: '2024-12-05' },
        { id: 'task-3', title: 'Task 3', status: 'todo', dueDate: '2024-12-10' }
      ];
      
      const result = await generateMilestones(tasks);
      
      assert.strictEqual(result.length, 3);
    });

    it('should use correct color from palette based on index', async () => {
      const tasks = [
        { id: 'task-1', title: 'Task 1', status: 'todo', dueDate: '2024-12-01' },
        { id: 'task-2', title: 'Task 2', status: 'todo', dueDate: '2024-12-10' },
        { id: 'task-3', title: 'Task 3', status: 'todo', dueDate: '2024-12-20' }
      ];
      
      const result = await generateMilestones(tasks);
      
      assert.strictEqual(result[0].color, MILESTONE_COLORS[0]);
      assert.strictEqual(result[1].color, MILESTONE_COLORS[1]);
      assert.strictEqual(result[2].color, MILESTONE_COLORS[2]);
    });

    it('should set isAutoGenerated to true', async () => {
      const tasks = [
        { id: 'task-1', title: 'Task 1', status: 'todo', dueDate: '2024-12-31' }
      ];
      
      const result = await generateMilestones(tasks);
      
      assert.strictEqual(result[0].isAutoGenerated, true);
    });

    it('should handle tasks with same deadline', async () => {
      const tasks = [
        { id: 'task-1', title: 'Task 1', status: 'todo', dueDate: '2024-12-31' },
        { id: 'task-2', title: 'Task 2', status: 'todo', dueDate: '2024-12-31' },
        { id: 'task-3', title: 'Task 3', status: 'todo', dueDate: '2024-12-31' }
      ];
      
      const result = await generateMilestones(tasks);
      
      assert.strictEqual(result.length, 1);
      assert.strictEqual(result[0].taskIds.length, 3);
    });

    it('should use milestone deadline as min date of cluster', async () => {
      const tasks = [
        { id: 'task-1', title: 'Task 1', status: 'todo', dueDate: '2024-12-01' },
        { id: 'task-2', title: 'Task 2', status: 'todo', dueDate: '2024-12-03' }
      ];
      
      const result = await generateMilestones(tasks);
      
      assert.strictEqual(result[0].deadline, '2024-12-01');
    });

    it('should generate title for milestone', async () => {
      const tasks = [
        { id: 'task-1', title: 'Task 1', status: 'todo', dueDate: '2024-12-01' }
      ];
      
      const result = await generateMilestones(tasks);
      
      assert.ok(result[0].title.length > 0);
    });
  });
});